### ISSUE TITLE
Six Tests Failing on JRuby because of OpenSSL issue

### ISSUE THREAD

**Issue by harrisj** [digidentity/xmlenc#14]
There is an issue with one of the cipher types and JRuby that causes six tests to fail with the same `data hash wrong` exception like this

```
  1) Xmlenc::Algorithms::RsaOaepMgf1p decrypt decrypts the cipher value
     Failure/Error: expect(subject.decrypt(cipher_value)).to be == key
     OpenSSL::PKey::RSAError:
       data hash wrong
     # ./lib/xmlenc/algorithms/rsa_oaep_mgf1p.rb:12:in `decrypt'
     # ./spec/lib/xmlenc/algorithms/rsa_oaep_mgf1p_spec.rb:14:in `(root)'
```

This seems to be [an issue with the default JRuby SSL library](https://github.com/jruby/jruby/issues/1819), and has been patched in the distinct [jruby-ssl](https://github.com/jruby/jruby-openssl/pull/54), but I don't know enough about the issue to either change any dependencies for this gem or make a fix in my local environment to confirm that resolves the issue. I'm noting it here in case you want to investigate or offer and guidance to JRuby users affected by this problem. Thank you.

**Comment by benoist** [comment]
I wouldn't mind changing the dependency for JRuby. So if adding the jruby-ssl gem to the gemspec solves the issues I'm fine with it :)

**Comment by harrisj** [comment]
I haven't really figured out what solves the issue to be honest. This is
starting to get out of my comfort zone

Sent from my iPhone

On Sep 26, 2015, at 1:11 PM, benoist <notifications@github.com> wrote:

I wouldn't mind changing the dependency for JRuby. So if adding the
jruby-ssl gem to the gemspec solves the issues I'm fine with it :)

—
Reply to this email directly or view it on GitHub
<https://github.com/digidentity/xmlenc/issues/14#issuecomment-143470421>.
